### ISSUE TITLE
Java spi实现

### ISSUE THREAD

**Issue by small-Teenager** [yzx66-net/Java_Review#1]
https://github.com/yzx66-net/Java_Review/blob/main/%E5%BF%85%E5%A4%87%E7%9F%A5%E8%AF%86/SPI%E6%9C%BA%E5%88%B6%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90.md
没有jdk spi机制的不足：

需要遍历所有的实现，并实例化，然后才能在循环中才能找到需要的实现，做不到按需加载 。
配置文件中只是简单的列出了所有的扩展实现，而没有给它们命名。导致在程序中很难去准确的引用它们，dubbo spi使用别名方便查找。
扩展如果依赖其他的扩展，做不到自动注入和装配。
不提供类似于Spring的IOC和AOP功能。
扩展很难和其他的框架集成，比如扩展里面依赖了一个Spring bean，原生的Java SPI不支持

**Comment by yzx-66** [comment]
好的，已补充
